apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: claw-testnet
commonAnnotations:
  claw.io/release-id: claw-3ba7d00362418d0dad1a9602f3c2ee8faaf18285
  delivery.claw.io/intent-digest: sha256:319be98bd8e40cf7ee15076641d76c96c7d9b9327dd6aabb929bc00dc8be9140
  delivery.claw.io/release-sha: "3ba7d00362418d0dad1a9602f3c2ee8faaf18285"
resources:
  - ../../../../../k8s/base
patches:
  - target:
      kind: Namespace|ServiceAccount|EndpointSlice|NetworkPolicy
    patch: |-
      $patch: delete
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: delete-selected-resources
  - target:
      kind: Service
      name: claw-(postgres|indexer-postgres|web|admin)
    patch: |-
      $patch: delete
      apiVersion: v1
      kind: Service
      metadata:
        name: delete-selected-resources
  - target:
      kind: Deployment
      name: claw-(indexer|web|admin)
    patch: |-
      $patch: delete
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: delete-selected-resources
images:
  - name: registry.invalid/claw/backend
    newName: 127.0.0.1:5000/claw/backend
    digest: sha256:86abde77f471072e672c9c4a9413115ff5d550b104cefbb3d7333e93b80377b8
