apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: claw-testnet
commonAnnotations:
  claw.io/release-id: claw-53ea57c4f7c676347edcde8952c4d8dcc657ed93
  delivery.claw.io/intent-digest: sha256:5e4833f40a7f078e5422d2bb3312a75e31744e7ce1bd8f56940c4e4378726123
  delivery.claw.io/release-sha: "53ea57c4f7c676347edcde8952c4d8dcc657ed93"
resources:
  - ../../../../../k8s/base
patches:
  - target:
      kind: Namespace|ServiceAccount|EndpointSlice|NetworkPolicy
    patch: |-
      $patch: delete
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: delete-selected-resources
  - target:
      kind: Service
      name: claw-(postgres|indexer-postgres|web|admin)
    patch: |-
      $patch: delete
      apiVersion: v1
      kind: Service
      metadata:
        name: delete-selected-resources
  - target:
      kind: Deployment
      name: claw-(indexer|web|admin)
    patch: |-
      $patch: delete
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: delete-selected-resources
images:
  - name: registry.invalid/claw/backend
    newName: 127.0.0.1:5000/claw/backend
    digest: sha256:09906e69670fffcef9a8e20ecd7d2257686a5aa3caff3fc4326c8948d2e6f81f
