apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: claw-testnet
commonAnnotations:
  delivery.claw.io/intent-digest: sha256:319be98bd8e40cf7ee15076641d76c96c7d9b9327dd6aabb929bc00dc8be9140
  delivery.claw.io/release-sha: "3ba7d00362418d0dad1a9602f3c2ee8faaf18285"
resources:
  - clawrelease.json
  - content-lock.yaml
configMapGenerator:
  - name: claw-service-configs
    files:
      - api.json=configuration/api.json
      - worker.json=configuration/worker.json
      - indexer.json=configuration/indexer.json
      - signer.json=configuration/signer.json
      - migration.json=configuration/migration.json
      - web.json=configuration/web.json
      - admin.json=configuration/admin.json
generatorOptions:
  disableNameSuffixHash: true
