apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: claw-testnet
commonAnnotations:
  delivery.claw.io/intent-digest: sha256:d30a97b13610f28beff4b923a316ba51088d73b1600103f0bd1c786f1cdb4758
  delivery.claw.io/release-sha: "42a1ae5c6d20f87ed375958a9cf12e52cf43df51"
resources:
  - clawrelease.json
  - content-lock.yaml
  - public-runtime-config.yaml
configMapGenerator:
  - name: claw-service-configs
    files:
      - api.json=configuration/api.json
      - worker.json=configuration/worker.json
      - indexer.json=configuration/indexer.json
generatorOptions:
  disableNameSuffixHash: true
