apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: claw-testnet
commonAnnotations:
  delivery.claw.io/intent-digest: sha256:b6528d9afb2348557fdcf5e4bb742ebd1bb411be070f291475b1c66a3823668c
  delivery.claw.io/release-sha: "65437300fb359c69eb322715357150434f8856bd"
resources:
  - clawrelease.json
  - content-lock.yaml
configMapGenerator:
  - name: claw-service-configs
    files:
      - api.json=configuration/api.json
      - worker.json=configuration/worker.json
      - indexer.json=configuration/indexer.json
      - signer.json=configuration/signer.json
      - migration.json=configuration/migration.json
      - web.json=configuration/web.json
      - admin.json=configuration/admin.json
generatorOptions:
  disableNameSuffixHash: true
