apiVersion: v1
kind: ConfigMap
metadata:
  name: claw-frontend-runtime-config
  namespace: claw-testnet
data:
  web-runtime-config.js: |
    globalThis.__CLAW_WEB_RUNTIME_CONFIG__={"MODE":"production","VITE_APP_URL":"https://157.254.194.180/","VITE_BSC_CHAIN_ID":97,"VITE_BSC_RPC_URL":"https://bsc-testnet-rpc.publicnode.com/","VITE_PUBLIC_API_URL":"https://157.254.194.180/api","VITE_PUBLIC_ASSET_LABEL":"测试资产","VITE_PUBLIC_CHAIN_LABEL":"BSC Testnet"};
  admin-runtime-config.js: |
    globalThis.__CLAW_ADMIN_RUNTIME_CONFIG__={"MODE":"production","VITE_ADMIN_API_URL":"https://157.254.194.180/api","VITE_PUBLIC_ASSET_LABEL":"测试资产","VITE_PUBLIC_CHAIN_LABEL":"BSC Testnet"};
