apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - service-accounts.yaml
  - database-endpoints.yaml
  - api.yaml
  - worker.yaml
  - web.yaml
  - admin.yaml
  - indexer-disabled.yaml
  - network-policies.yaml
