apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: claw-testnet
commonAnnotations:
  claw.io/release-id: claw-a22990fd372523a571373f15c8d3c70bc770bdb9
  delivery.claw.io/intent-digest: sha256:9498199ab9bda958f92f019ae296bbdb6122486074a574aacfb270b85ded7965
  delivery.claw.io/release-sha: "a22990fd372523a571373f15c8d3c70bc770bdb9"
resources:
  - ../../../../../k8s/base
  - public-entry.yaml
patches:
  - target:
      kind: Namespace|ServiceAccount|EndpointSlice|NetworkPolicy
    patch: |-
      $patch: delete
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: delete-selected-resources
  - target:
      kind: Service
      name: claw-(postgres|indexer-postgres|api)
    patch: |-
      $patch: delete
      apiVersion: v1
      kind: Service
      metadata:
        name: delete-selected-resources
  - target:
      kind: Deployment
      name: claw-(api|worker|indexer)
    patch: |-
      $patch: delete
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: delete-selected-resources
images:
  - name: registry.invalid/claw/web
    newName: 127.0.0.1:5000/claw/web
    digest: sha256:8a9d498186da278acf946b330c8b899fa45b5ca38c419f4baad9a7939edebd42
  - name: registry.invalid/claw/admin
    newName: 127.0.0.1:5000/claw/admin
    digest: sha256:fa1d9f206e1bb629a8390dabd3f5424e4f0dfdd5df997650fb8d40f41500bf86
