apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: claw-testnet
commonAnnotations:
  claw.io/release-id: claw-65437300fb359c69eb322715357150434f8856bd
  delivery.claw.io/intent-digest: sha256:b6528d9afb2348557fdcf5e4bb742ebd1bb411be070f291475b1c66a3823668c
  delivery.claw.io/release-sha: "65437300fb359c69eb322715357150434f8856bd"
resources:
  - ../../../../../k8s/base
  - public-entry.yaml
patches:
  - target:
      kind: Namespace|ServiceAccount|EndpointSlice|NetworkPolicy
    patch: |-
      $patch: delete
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: delete-selected-resources
  - target:
      kind: Service
      name: claw-(postgres|indexer-postgres|api)
    patch: |-
      $patch: delete
      apiVersion: v1
      kind: Service
      metadata:
        name: delete-selected-resources
  - target:
      kind: Deployment
      name: claw-(api|worker|indexer)
    patch: |-
      $patch: delete
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: delete-selected-resources
images:
  - name: registry.invalid/claw/web
    newName: 127.0.0.1:5000/claw/web
    digest: sha256:37d5039dbd74a4efa135a7c79490f8bd348cda4518b02047a2344eaf315aa6b5
  - name: registry.invalid/claw/admin
    newName: 127.0.0.1:5000/claw/admin
    digest: sha256:8b0149fd2d91c2559733ce3753622fa1755bc9b66354b3adca3ada82cd78f9d3
