apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: claw-testnet
commonAnnotations:
  claw.io/release-id: claw-53ea57c4f7c676347edcde8952c4d8dcc657ed93
  delivery.claw.io/intent-digest: sha256:5e4833f40a7f078e5422d2bb3312a75e31744e7ce1bd8f56940c4e4378726123
  delivery.claw.io/release-sha: "53ea57c4f7c676347edcde8952c4d8dcc657ed93"
resources:
  - ../../../../../k8s/base
  - public-entry.yaml
patches:
  - target:
      kind: Namespace|ServiceAccount|EndpointSlice|NetworkPolicy
    patch: |-
      $patch: delete
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: delete-selected-resources
  - target:
      kind: Service
      name: claw-(postgres|indexer-postgres|api)
    patch: |-
      $patch: delete
      apiVersion: v1
      kind: Service
      metadata:
        name: delete-selected-resources
  - target:
      kind: Deployment
      name: claw-(api|worker|indexer)
    patch: |-
      $patch: delete
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: delete-selected-resources
images:
  - name: registry.invalid/claw/web
    newName: 127.0.0.1:5000/claw/web
    digest: sha256:3ea7f4671b610f8f113630bb624d20c88553724375ceb204c9aa04509fef8432
  - name: registry.invalid/claw/admin
    newName: 127.0.0.1:5000/claw/admin
    digest: sha256:d3f62eff8cd811a4ff459662ff27218076a530f6f6ce1d425fa2fc69bdade8ab
